package com.example.c_otomatch.utils

import com.example.c_otomatch.R
import com.example.c_otomatch.models.Car

object Data {
    val carList = listOf(
        Car(
            id = 1,
            name = "Civic Turbo",
            brand = "Honda",
            year = 2021,
            price = "Rp 420.000.000",
            mileage = "20.000 km",
            location = "Tangerang",
            imageResId = R.drawable.civic,
            isWishlist = false,
            isSold = false,
            sellerName = "Callista Jasmine",
            sellerContact = "081234567890",
            bodyType = "Sedan",
            color = "Hitam",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<50.000 km"
        ),
        Car(
            id = 2,
            name = "Fortuner VRZ",
            brand = "Toyota",
            year = 2020,
            price = "Rp 520.000.000",
            mileage = "35.000 km",
            location = "Jakarta",
            imageResId = R.drawable.fortuner,
            isWishlist = false,
            isSold = false,
            sellerName = "Callista Jasmine",
            sellerContact = "081234567890",
            bodyType = "SUV",
            color = "Putih",
            transmission = "Automatic",
            fuel = "Diesel",
            kmRange = "50.000-100.000 km"
        ),
        Car(
            id = 3,
            name = "Xpander Ultimate",
            brand = "Mitsubishi",
            year = 2019,
            price = "Rp 250.000.000",
            mileage = "40.000 km",
            location = "Bekasi",
            imageResId = R.drawable.xpander,
            isWishlist = false,
            isSold = false,
            sellerName = "Budi Santoso",
            sellerContact = "082233445566",
            bodyType = "MPV",
            color = "Silver",
            transmission = "Manual",
            fuel = "Bensin",
            kmRange = "50.000-100.000 km"
        ),
        Car(
            id = 4,
            name = "Mazda 3",
            brand = "Mazda",
            year = 2022,
            price = "Rp 480.000.000",
            mileage = "10.000 km",
            location = "BSD City",
            imageResId = R.drawable.mazda3,
            isWishlist = false,
            isSold = false,
            sellerName = "Andi Wijaya",
            sellerContact = "083344556677",
            bodyType = "Sedan",
            color = "Biru",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<50.000 km"
        ),
        Car(
            id = 5,
            name = "Tesla Model 3",
            brand = "Tesla",
            year = 2023,
            price = "Rp 1.200.000.000",
            mileage = "5.000 km",
            location = "Jakarta Selatan",
            imageResId = R.drawable.tesla_model3,
            isWishlist = false,
            isSold = false,
            sellerName = "Kevin Lim",
            sellerContact = "081122334455",
            bodyType = "Sedan",
            color = "Putih",
            transmission = "Automatic",
            fuel = "Listrik",
            kmRange = "<10.000 km"
        ),
        Car(
            id = 6,
            name = "BMW X5",
            brand = "BMW",
            year = 2021,
            price = "Rp 1.600.000.000",
            mileage = "25.000 km",
            location = "Jakarta Barat",
            imageResId = R.drawable.bmw_x5,
            isWishlist = false,
            isSold = false,
            sellerName = "Jonathan",
            sellerContact = "081278945612",
            bodyType = "SUV",
            color = "Hitam",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<50.000 km"
        ),
        Car(
            id = 7,
            name = "Mercedes-Benz E200",
            brand = "Mercedes-Benz",
            year = 2020,
            price = "Rp 1.250.000.000",
            mileage = "30.000 km",
            location = "Jakarta Utara",
            imageResId = R.drawable.mercedes_e200,
            isWishlist = false,
            isSold = false,
            sellerName = "Agus Setiawan",
            sellerContact = "082188889999",
            bodyType = "Sedan",
            color = "Silver",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "20.000-50.000 km"
        ),
        Car(
            id = 8,
            name = "Jeep Wrangler Rubicon",
            brand = "Jeep",
            year = 2018,
            price = "Rp 1.000.000.000",
            mileage = "60.000 km",
            location = "Bandung",
            imageResId = R.drawable.jeep_rubicon,
            isWishlist = false,
            isSold = false,
            sellerName = "Rina Oktaviani",
            sellerContact = "081345678912",
            bodyType = "SUV",
            color = "Merah",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "50.000-100.000 km"
        ),
        Car(
            id = 9,
            name = "Volkswagen Beetle Classic",
            brand = "Volkswagen",
            year = 1974,
            price = "Rp 180.000.000",
            mileage = "120.000 km",
            location = "Yogyakarta",
            imageResId = R.drawable.vw_beetle,
            isWishlist = false,
            isSold = false,
            sellerName = "Hendra Gunawan",
            sellerContact = "081311122233",
            bodyType = "Coupe",
            color = "Kuning",
            transmission = "Manual",
            fuel = "Bensin",
            kmRange = ">100.000 km"
        ),
        Car(
            id = 10,
            name = "Suzuki Jimny",
            brand = "Suzuki",
            year = 2023,
            price = "Rp 420.000.000",
            mileage = "8.000 km",
            location = "Tangerang Selatan",
            imageResId = R.drawable.jimny,
            isWishlist = false,
            isSold = false,
            sellerName = "Dewi Anggraini",
            sellerContact = "085678901234",
            bodyType = "SUV",
            color = "Hijau Army",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<10.000 km"
        ),
        Car(
            id = 11,
            name = "Hyundai Ioniq 5",
            brand = "Hyundai",
            year = 2024,
            price = "Rp 850.000.000",
            mileage = "3.000 km",
            location = "BSD City",
            imageResId = R.drawable.ioniq5,
            isWishlist = false,
            isSold = false,
            sellerName = "Tania Widjaja",
            sellerContact = "081800112233",
            bodyType = "Crossover",
            color = "Abu-abu",
            transmission = "Automatic",
            fuel = "Listrik",
            kmRange = "<10.000 km"
        ),
        Car(
            id = 12,
            name = "Toyota Kijang Super",
            brand = "Toyota",
            year = 1996,
            price = "Rp 65.000.000",
            mileage = "180.000 km",
            location = "Cirebon",
            imageResId = R.drawable.kijang_super,
            isWishlist = false,
            isSold = false,
            sellerName = "Slamet Riyadi",
            sellerContact = "081366778899",
            bodyType = "MPV",
            color = "Hijau Tua",
            transmission = "Manual",
            fuel = "Bensin",
            kmRange = ">100.000 km"
        ),
        Car(
            id = 13,
            name = "Range Rover Evoque",
            brand = "Land Rover",
            year = 2022,
            price = "Rp 1.750.000.000",
            mileage = "12.000 km",
            location = "Jakarta Pusat",
            imageResId = R.drawable.evoque,
            isWishlist = false,
            isSold = false,
            sellerName = "William Tanuwijaya",
            sellerContact = "081700334455",
            bodyType = "SUV",
            color = "Putih Mutiara",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<20.000 km"
        ),
        Car(
            id = 14,
            name = "Daihatsu Ayla",
            brand = "Daihatsu",
            year = 2021,
            price = "Rp 135.000.000",
            mileage = "25.000 km",
            location = "Serpong",
            imageResId = R.drawable.ayla,
            isWishlist = false,
            isSold = false,
            sellerName = "Riko Santoso",
            sellerContact = "082190112233",
            bodyType = "Hatchback",
            color = "Merah",
            transmission = "Automatic",
            fuel = "Bensin",
            kmRange = "<50.000 km"
        ),
        Car(
            id = 15,
            name = "Nissan Leaf",
            brand = "Nissan",
            year = 2023,
            price = "Rp 700.000.000",
            mileage = "6.000 km",
            location = "Jakarta Selatan",
            imageResId = R.drawable.nissan_leaf,
            isWishlist = false,
            isSold = false,
            sellerName = "Angga Saputra",
            sellerContact = "081299887766",
            bodyType = "Hatchback",
            color = "Putih",
            transmission = "Automatic",
            fuel = "Listrik",
            kmRange = "<10.000 km"
        )
    )
}
